services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: eskimo-fe
    container_name: eskimo-tegar
    ports:
      - "3003:80"
    restart: unless-stopped
    networks:
      - eskimo-network

networks:
  eskimo-network:
    driver: bridge